### ISSUE TITLE
Create an option for forcing window position

### ISSUE THREAD

**Issue by EgZvor** [wellle/context.vim#1]
I have `set splitbelow` in my vimrc, but I still want the context to show up above. You can use `aboveleft` or `belowright` modifiers to the `pedit` command to force either one.

**Comment by wellle** [comment]
@EgZvor: Thank you!

I just changed it in #2 to just always use `aboveleft` to force it above. I don't see why anyone would want it below, so I'll wait and see if someone actually needs this option.
