### ISSUE TITLE
Do not let cursor focus into the context window

### ISSUE THREAD

**Issue by voldikss** [wellle/context.vim#108]
Sometimes when I was jumping between several windows, I suddenly jumped into the context window, which gives me a bad experience.

Could we forbidden users to jump into the context window?

Possible solution:

Add a local BufEnter event to the context buffer, every time user put cursor into the context window, close the context window (`wincmd c`) or jump again to the next window (`wincmd w`).

**Comment by wellle** [comment]
Hey, can you tell me if you are using an older version of Vim or Neovim or if you are setting `g:context_presenter` to some value? Never versions of Vim/Neovim should use popups/floating windows by default which you should not be able to navigate to. It's only the legacy support for older versions using the preview window which you would be able to navigate to. If you can, I would suggest you use floats/popups for a much better experience. Let me know if this doesn't work for you.

**Comment by voldikss** [comment]
The issue was gone. Nice plugin! :+1:
