### ISSUE TITLE
Plugin breaks vim's visual-block append.

### ISSUE THREAD

**Issue by husixu1** [wellle/context.vim#114]
I found this plugin breaking vim's visual-block append feature (`:h v_b_A`). 

Steps to reproduce: 

1. Open a text file with the following content:
	```
	111
	222222
	333
	```
2. Place cursor anywhere and press key sequence `vip<C-v>$A444<Esc>`

Expected result:

	111444
    222222444
    333444

Result when context.vim is enabled:

	111 444
	222244422
	333 444

This seems to be related to #84. I think the `setpos('.', cursor)` call in `autoload/context/util.vim` breaks this functionality. I haven't found a perfect solution yet, but ruling out visual block mode works for me:

```diff
diff --git a/autoload/context/util.vim b/autoload/context/util.vim
index 5b6db1b..67f2390 100644
--- a/autoload/context/util.vim
+++ b/autoload/context/util.vim
@@ -121 +121,3 @@ function! context#util#update_state() abort
-    call setpos('.', cursor)
+    if match("\<C-v>", mode()) == -1
+        call setpos('.', cursor)
+    endif
```

**Comment by KnoP-01** [comment]
One can work around this bug by pressing $ two times. Not a solution though.

**Comment by wellle** [comment]
@husixu1: Thank you for your detailed report. I added your suggestion in https://github.com/wellle/context.vim/pull/116 👍
