### ISSUE TITLE
remove <context.vim> in the upper right corner

### ISSUE THREAD

**Issue by gitzhangzhao** [wellle/context.vim#118]
Hello, the plugin is good to use, but can I remove the plugin name in the upper right corner
![图片](https://user-images.githubusercontent.com/60341709/171900773-14da221f-35f9-4df9-a373-2da625dc0027.png)

**Comment by wellle** [comment]
Yes, try this (it's mentioned in the readme):
```vim
let g:context_highlight_tag = '<hide>'
```

**Comment by gitzhangzhao** [comment]
Thank you very much, I didn't notice this

**Comment by aselker** [comment]
I also wanted to do this, and only figured out how by looking through the list of closed issues.  Might be worth describing what "the tag" is in the README.
