### ISSUE TITLE
Enable on specific filetype only

### ISSUE THREAD

**Issue by jasonkena** [wellle/context.vim#20]

**Comment by wookayin** [comment]
For example, helpfile should be blacklisted. e.g. `help botright`:

```
Error detected while processing function context#update[47]..context#preview#update_context[18]..<SNR>179_show:
line   24:
E21: Cannot make changes, 'modifiable' is off:     silent 0put =a:lines " paste lines
E434: Can't find tag pattern
```

**Comment by knubie** [comment]
If you're using vim-plug, you can specify which filetypes should activate the plugin.

https://github.com/junegunn/vim-plug#plug-options

**Comment by jasonkena** [comment]
But after the plugin is active, it will still work on all the filetypes right?

**Comment by wellle** [comment]
@wookayin: Thanks for pointing out the issue with help pages. This is a regression introduced in #22. I'll fix that soon 👍 

As for disabling per filetype, I agree that's a good idea. Someone already opened a PR #21 which I will get back to soon. Stay tuned. 🙏

**Comment by wellle** [comment]
@wookayin: The issue you reported regarding the help buffers has been fixed in https://github.com/wellle/context.vim/pull/25. Thanks again!
