### ISSUE TITLE
Flickering behavior due to redrawing

### ISSUE THREAD

**Issue by wookayin** [wellle/context.vim#23]
This is a fantastic plugin -- great idea, I like it pretty much.

One small thing that annoys me is that, whenever I scroll (e.g. press `j` many times) the buffer, all the buffer contents seem to be redrawn and because of this the vim screen flickers. Any solution to this?

I am using neovim 0.4.3 (linux), `TERM=xterm-256color` with `termguicolors` enabled.

**Comment by wookayin** [comment]
Additional information: Without floating windows (i.e. `g:context_presenter = 'preview'`), it works well without flickering.

**Comment by wellle** [comment]
@wookayin: Thanks! Yeah I wish we wouldn't need the hard redraw. There's a redraw issue in Neovim's floating window implementation, I opened an issue about it here: https://github.com/neovim/neovim/issues/11597

If you want to try this plugin without that redraw, you try use this branch:
https://github.com/wellle/context.vim/compare/23-nvim-no-redraw

**Comment by wookayin** [comment]
Thanks @wellle for the information; it is super helpful. Temporarily disabling redraw (`:mode`) makes me feel more comfortable, and I would work around with this. Look forward to the upstream neovim issue being fixed.

**Comment by syphar** [comment]
I also switched to the version without redraw because of the flickering and performance. 

(and yes, sometimes there are small rendering issues / remains of the closed context, but that annoys me less than the performance / flicker)

**Comment by exdeniz** [comment]
I have this issues on start nvim from tmux. Switching to 23-nvim-no-redraw and problem solved.

**Comment by wookayin** [comment]
Hey @wellle, would you want to make this feature merged to master but actually configurable by some `g:` variable?

**Comment by wellle** [comment]
Yes that sounds like a good idea 👍

**Comment by wellle** [comment]
@wookayin @sirupsen @lervag @jasonkena @exdeniz: I added a setting in #66 so you can disable the redraw on updated master now. Add this to your vimrc:
```vim
let g:context_nvim_no_redraw = 0
```

**Comment by lervag** [comment]
I still experience quite severe flickering, both with and without this setting.

**Comment by jasonkena** [comment]
@lervag @wellle Pretty sure it should be
`let g:context_nvim_no_redraw = 1`

**Comment by lervag** [comment]
Ah, yes. My brain was doing something else, sorry. With that, I can confirm there is no flickering, but I do see the artifacts. :\

**Comment by wellle** [comment]
@jasonkena: Thanks, fixed above 👍
