### ISSUE TITLE
Undefined variable: v:vim_did_enter on old versions of vim

### ISSUE THREAD

**Issue by idbrii** [wellle/context.vim#28]
Context doesn't do any kind of version check in plugin/context.vim.

Not sure what other features you use, but maybe add a check to the top:

```vim
if v:version < 800 | finish | endif
```

On vim 7.4.52 (ubuntu) I see:

* Undefined variable: v:vim_did_enter
* Unknown function: win_getid

(I have some machines with old vim but the same config.)

**Comment by wellle** [comment]
Thank you! I added a version check in #29 👍
