### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by toddyamakawa** [wellle/context.vim#30]
For this example, I clone https://github.com/tmux/tmux and opened screen-redraw.c
![image](https://user-images.githubusercontent.com/7848869/73551196-94cccc00-440b-11ea-87a7-39640b1a7dea.png)

I don't see syntax highlighting using the jellybeans colorscheme in the context window.

Here's my full vimrc:
https://github.com/toddyamakawa/vim

**Comment by toddyamakawa** [comment]
Turns out I goofed pretty hard. I was setting my syntax to "on"
Here's my commit where I fixed my issue. Nothing wrong on context.vim's end!
https://github.com/toddyamakawa/vim/commit/a35ee96d8d3f33db89a807e24e1e4f4e01a41035

**Comment by wellle** [comment]
Haha, nice! Thanks for taking the time to come back and close this issue! ❤️
