### ISSUE TITLE
The context window will sometimes move left

### ISSUE THREAD

**Issue by toddyamakawa** [wellle/context.vim#31]
Using the same example as issue #30, notice how the "if" keyword is slightly misaligned?
![image](https://user-images.githubusercontent.com/7848869/73551329-d0679600-440b-11ea-9c31-057320834809.png)

If I move one line up, it will align properly:
![image](https://user-images.githubusercontent.com/7848869/73551441-01e06180-440c-11ea-81ed-51b1e6236ef6.png)

**Comment by wellle** [comment]
Thanks, I can reproduce this one. It's related to `:set list`. If you try `:set nolist` then this doesn't happen.  I'll see if I can fix that.

**Comment by wellle** [comment]
Fixed in #33, thanks for reporting 👍
