### ISSUE TITLE
Peek context hierarchy

### ISSUE THREAD

**Issue by rafi** [wellle/context.vim#38]
Navigating long structured hierarchies can be tiresome especially in indentation-based code like YAML and Python. However, the context floating window and plugin mechanics can often feel like an over-kill, while all I want is taking a peek on the topmost hierarchy levels, so I can take a quick mental-note.
It would be awesome having a shortcut for opening context.vim floating window only once, as a sheer pop-up overview, and disappear after cursor movement, without any other side-effects. As all the mechanics exist already for rendering the popup's content, I hope you see this suggestion as valuable as I  😃

**Comment by wellle** [comment]
Thank you! I have a small prototype working, but will have to do some cleanups before it becomes useful. I'll get back to you.

**Comment by wellle** [comment]
@rafi @nilsboy: I pushed something to branch `38-peek`. Could you try that one? It adds a command `:ContextPeek`. Thank you!

**Comment by nilsboy** [comment]
Seems to work great - tested neovim with float and preview.
Thank you!
