### ISSUE TITLE
Question: context window color

### ISSUE THREAD

**Issue by CharlesGueunet** [wellle/context.vim#4]
Hello,

Thanks for your plugin,
is there a way to change the color of the text in the context window OR to add a clear separator between the context window and the current text ? I would like to have a clear distinction between my code and the context given by this plugin :)

Best,
Charles

**Comment by monkoose** [comment]
I think the most benefit would be with use of vim popups and neovim floating windows. Because you can easily set different background highlighting for this windows. And it will remove resize windows problem as well.

**Comment by wellle** [comment]
@CharlesGueunet @monkoose @itchyny @tversteeg: I just merged https://github.com/wellle/context.vim/pull/22 which adds support for popup/floating windows. And their highlighting is customizable. Please let me know if that works for you!
