### ISSUE TITLE
Add option to disable ellipis

### ISSUE THREAD

**Issue by nilsboy** [wellle/context.vim#41]
The ellipis adds too much noise for my taste - an option would be great!
Especially with arrays of objects in JSON-Files it may result in `{ ··· }, { ··· }, { ··· }, { ··· }, {`

Thank you!

**Comment by wellle** [comment]
@nilsboy: There is an option to customize it: `let g:context_ellipsis_char = '·'`, see the README. Does that work for you?

**Comment by nilsboy** [comment]
@wellle: I tried that - I'd rather not see the curlies at all.

**Comment by wellle** [comment]
Yeah I agree the array of objects in JSON is somewhat noisy. I'll think about it 👍

**Comment by wellle** [comment]
@nilsboy: I made some changes and pushed to branch `41-join-short`. Let's look at an example context (default settings):
<img width="622" alt="Screenshot 2020-02-06 20 38 07" src="https://user-images.githubusercontent.com/474504/73972368-0384ba80-4921-11ea-8db8-dd479c120e47.png">

With `let g:context_max_join_parts  = 2` (I like this one):
<img width="624" alt="Screenshot 2020-02-06 20 38 31" src="https://user-images.githubusercontent.com/474504/73972401-14cdc700-4921-11ea-8576-c804e1c125ea.png">

With `let g:context_max_join_parts  = 1`:
<img width="619" alt="Screenshot 2020-02-06 20 38 43" src="https://user-images.githubusercontent.com/474504/73972422-1dbe9880-4921-11ea-8ff1-d5f0919153a4.png">

Please give it a shot and let me know what you think 👍

**Comment by nilsboy** [comment]
This is great!
I like the last one better because I usually don't care if there are any entries before the current one - but it might come in handy in some situations.

Thank you again!

Please do merge.

**Comment by wellle** [comment]
Done, thanks again!
