### ISSUE TITLE
Custom indent function

### ISSUE THREAD

**Issue by maxigit** [wellle/context.vim#44]
I've been using this plugin for a couple weeks and I'm loving it. However, It will be nice if it could work with headings like markdown or org-mode (#, ##, ### ) (and even better with both indent and heading at the same time). I notice the code use the build-in `indent` function, will it be possible to allows the user to use is own function ?

**Comment by wellle** [comment]
Thank you! I got this request before, let me link it for reference: https://www.reddit.com/r/vimplugins/comments/e7lby3/welllecontextvim_vim_plugin_that_shows_the/fa353fv/

I'll keep this issue open as a reminder for that, but it might take some time before I get to that :v:

**Comment by maxigit** [comment]
What I'm asking is actually fairly simple (and I tried it in a dirty way ).
You just need to replace all the calls to `indent` by `g:context_indent`
and initialize it with `funcref(indent)`.
Then people can just set there own indent function. For markdown is
something like

 function MDLevel(line)
      return search(line, "^##* ")
endfunction

to get both indent AND heading something like
`MDLevel(line)+indent(line)+5` should work.

Basic `foldlevel` method (only using number)` should work straight of the
box.
