### ISSUE TITLE
Resizing a split does not resize the context window

### ISSUE THREAD

**Issue by nkakouros** [wellle/context.vim#46]
I am using Neovim:

```
NVIM v0.5.0-357-g405f49a9b
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/include
```

I have installed context.vim using vim-plug. These are the only two plugins running and (as far as I could tell) there was no other config going on, but the installation of the two plugins and context.vim's config:

```
  let g:context_border_char = '━'
  let g:context_filetype_blacklist = ['nerdtree', 'help']
```

I have two vertical splits:
![Screenshot_20200206_223309](https://user-images.githubusercontent.com/11805218/73980541-557d0e80-4928-11ea-8eed-10d7a724c7b5.png)

Pressing in normal mode `10<C-w> <` (10 ctrl-w <), results in:

![Screenshot_20200206_223320](https://user-images.githubusercontent.com/11805218/73980554-6037a380-4928-11ea-869b-6e1f2bc0652a.png)

The context.vim window does not get resized.

**Comment by wellle** [comment]
Thank you, I can reproduce it. Will look into it 👍

**Comment by wellle** [comment]
@nkakouros: I pushed a change to branch `46-disabled-update-layout`. Could you try again on that one and let me know if that fixes this issue for you? Thanks!

**Comment by nkakouros** [comment]
I just pulled the master branch and the issue remains.

**Comment by wellle** [comment]
@nkakouros: Hmm. The redraw is supposed to be triggered by the `CursorHold` autocommand, which triggers after `updatetime` of inactivity. Can you run these two commands in Vim and show me the output?

```
:set updatetime?
```
```
:autocmd CursorHold
```

Output on my machine:
```
  updatetime=100
```
```
--- Autocommands ---
context.vim  CursorHold
    *         call context#update('CursorHold')
```

**Comment by nkakouros** [comment]
```
:set updatetime?
updatetime=4000

:autocmd CursorHold                                                                                       
--- Autocommands ---
context.vim  CursorHold
    *         call context#update('CursorHold')
```

Setting `updatetime` to 100, I can see the resizing happeing. So, it was working but I had to wait 4 seconds. So, this seems fixed! :rocket:

**Comment by wellle** [comment]
That's great, thank you!
