### ISSUE TITLE
Make async, or faster?

### ISSUE THREAD

**Issue by ChrisPenner** [wellle/context.vim#5]
Very cool idea! Unfortunately it's far too slow for me to use; it prevents me from navigating around. Perhaps you could allow shelling out to a very fast grepper like `rg`, or somehow run everything asynchronously in the background so it doesn't slow down the editor?

Cheers!

**Comment by wellle** [comment]
Thanks for opening this issue!

I'll try adding some caching. I think that should work well. 🤞

**Comment by seagoj** [comment]
I am very much into this idea, but it seemed a little slow especially with larger files. I'd be happy to beta test or help any way I can. Thanks

**Comment by wellle** [comment]
Thank you! Can you tell me what Vim/Neovim version you're using?

And maybe even provide an example file and describe where it's slow?

**Comment by wellle** [comment]
@ChrisPenner @seagoj: I added some caching in #15. Can you try again and let me know if that helped? Thanks!
