### ISSUE TITLE
Conflict with vim-scrolloff-fraction when using the `nvim-float` presenter

### ISSUE THREAD

**Issue by nkakouros** [wellle/context.vim#59]
I might be asking too much, but there is a conflict with the [vim-scrolloff-fraction](https://github.com/drzel/vim-scrolloff-fraction) plugin.

When both plugins are enabled, pressing `zt` actually moves the cursor. Using the `preview` presenter solves the issue, but does not look as good! :-D

Do you think it is possible to have both plugins work side by side?

**Comment by wellle** [comment]
Thanks. I might look into this at some point. It'll have low priority for me though.

**Comment by nkakouros** [comment]
Perhaps it is easier to solve this on the other plugin's side. I show that they all they do is:

```
autocmd BufEnter,WinEnter,WinNew,VimResized *,*.*
        \ call ScrollOffFraction(g:scrolloff_fraction)
```

and that function sets `&scrolloff`. Maybe, if I expand this autocommand to run on a context-window-appeared/resized event, the problem could go away. Is there such an event I could try out?
