### ISSUE TITLE
Some error pops up randomly

### ISSUE THREAD

**Issue by NeoHuang** [wellle/context.vim#6]
sometimes this error shows up and the plugin seems deactivated afterwards, I have to restart vim in order to make it work again
```
Error detected while processing function context#update[27]..<SNR>108_update_context[131]..<SNR>108_show_in_preview:
line   39:
E441: There is no preview window
```

**Comment by wellle** [comment]
Thanks! As discussed I couldn't reproduce it, but this case should be properly handled now. If it fails to open the preview window, it now silently aborts. Please try again and let me know if!
