### ISSUE TITLE
Option to disable border and tag

### ISSUE THREAD

**Issue by lervag** [wellle/context.vim#62]
Thanks for this plugin, it seems very useful!

I would be happy if I could disable the border and tag line. Since I use a slightly different background on the context buffer, I don't really need that line.

On a similar note, I also think it should be possible to remove/disable the tag in the border.

**Comment by wellle** [comment]
Thank you! I will consider adding this. 👍 

(I'd like to finish work on #42 first though)

**Comment by lervag** [comment]
Great, thanks! No rush :)

Btw, in the meantime, I find it looks good to use space as the border character.

**Comment by wellle** [comment]
Protip: Use double space to push the tag out of sight 😉 
```vim
let g:context_border_char = '  '
```

**Comment by lervag** [comment]
Haha, thanks! Still, I hope you consider to add this feature regardless of this workaround :)

**Comment by wellle** [comment]
@lervag @ThomasFeher: This has been added in #67 :v:

**Comment by lervag** [comment]
Great, thanks! I'm very happy to see that you continue to develop this plugin and I find I really enjoy keeping it activated!
