### ISSUE TITLE
Setting g:Context_indent per filetype

### ISSUE THREAD

**Issue by lervag** [wellle/context.vim#63]
Is it possible to set `g:Context_indent` to a different value for different file types? I have one filetype that I currently blacklist, but would want to specify an indent function for it to make it work.

I can describe this in more detail if necessary.

**Comment by wellle** [comment]
Can't you make the function behave differently depending on the filetype?

**Comment by lervag** [comment]
Perhaps I misunderstand this. What I want is to keep the default behaviour in general, but to specify a different function to parse the context for markdown (or related) files. In particular, I have a collection of notes with `.wiki` extension that is mainly markdown formatted, but I use my own filetype for it. I want the same behaviour for this filetype as for normal markdown. This might already be possible in some other way?

If I understand correctly, the main idea here is to use indentations to guide the context. But this is not possible for markdown files. So I assume you have a different mechanism here?

**Comment by wellle** [comment]
I mean something like this (untested):
```vim
function MyIndent(line)
    if &ft == 'markdown'
        " some custom implementation for markdown
        let indent = indent(a:line)
        if indent < 0
            return indent
        endif
        let line = getline(a:line)
        let headings = match(line, '^*\+\zs\s')+1
        if headings <= 0
            let headings = match(line, '^#\+\zs\s')+1
            if headings <= 0
                let headings = 5
            endif
        endif
        return indent+headings
    elseif &ft == 'wiki'
        " TODO: implementation for .wiki
    else
        " fall back to default implementation
        return indent(a:line)
    endif
endfunction
let g:Context_indent = funcref('MyIndent')
```

**Comment by lervag** [comment]
Ah, thanks. Then I understand. I think this resolves my issue. Again, thanks!
