### ISSUE TITLE
line number and jumping to context line

### ISSUE THREAD

**Issue by maxigit** [wellle/context.vim#69]
It would be nice to be able to jump to a line you can see the context window (like when you press `H`).
I personnaly will be happy for it to be mapped to `<count>H` but any mapping will do.
Alternatively, displaying the line number in the context window (in accordance with `set number` and `set relativenumber` would help.

**Comment by wellle** [comment]
Interesting idea!

FWIW what I'm currently using for this: With https://github.com/jeetsukumaran/vim-indentwise you can type `[-` to jump through the context lines by decreasing indentation.

As for showing line numbers we have #40.

**Comment by maxigit** [comment]
I didn't know about vim-indentwise which seems quite cool indeed.
To get why I want I'll need `0[_` instead of `[-` but that's a details.
However, an alternative to this (and displaying line number) would be to set number in the context window (which I understand will display `1`, `2`, `3` etc which can then be used in combination with `H` so that `1H` goes to the first context, line, `2H` the second etc ...
To do so, It seems that you only need to store the line number as well as the line in `w:context` and use it.

**Comment by wellle** [comment]
@maxigit: I just added support for line numbers in #81. So if you `:set relativenumber` you can use the displayed relative line numbers to jump to the context lines. Would you say that's enough to close this issue? Thank you!

**Comment by wellle** [comment]
![context-example](https://user-images.githubusercontent.com/474504/91095944-78210b80-e65d-11ea-9a95-76c7982470f1.png)

For example in this screenshot if you want to jump to the `VAR_FUNC` line (third context line) you could type `52k`.

**Comment by maxigit** [comment]
That's brilliant and should fulfill all my needs ( I see it works for both
relative and normal numbers which is great).
However, I got an error

    E28: No such highlight group name: Whitespace

Other than that , I really like the separator in the margin ;-)

**Comment by wellle** [comment]
@maxigit: Thanks for reporting, this has been fixed in https://github.com/wellle/context.vim/pull/82. Please try again 🙏

**Comment by maxigit** [comment]
It works now. Thanks

**Comment by wellle** [comment]
Cool, I'll close this issue then. Thanks again!

**Comment by maxigit** [comment]
There is also a new issue (maybe only for me), but now, lines in the
context view are indented regardless of their physical original
indentation which is really disturbing
when the indentation level is not based on the indentation but on something
else (like markdown). For example I use `-- *` `-- **` in haskel to indent
level 1,2 etc and then start "normal" indentation to 5.

Example
the code

    -- * Util
    f :: a -> [a]
    f x =  [x]

Becomes

    -- * Util
          f :: a -> [a]
           ===============context.vim
    f x = [x]


Instead of (as it used to be ....)



    -- * Util
    f :: a -> [a]
    ===============context.vim
    f x = [x]

Why as this changed been introduced ???

**Comment by wellle** [comment]
Thank you for reporting this.

To be fully honest I am aware of this and had already started working on fixing it, but then wondered if people are actually using custom indent functions. So I decided to just release #81 and see if someone complains about it. So I have taken notice and will fix this 👍

**Comment by wellle** [comment]
@maxigit: I fixed it in #85. Please have a look at the PR description as this changes the return value of the custom indent functions. Please let me know if anything is unclear or still not working as expected. Thanks again!

**Comment by maxigit** [comment]
It seems to be working now. Many thanks.
I like the warning the indent function is not configured properly :-)
