### ISSUE TITLE
Vim code is inserted when using `<c-o>zz` in insert mode

### ISSUE THREAD

**Issue by nkakouros** [wellle/context.vim#70]
Steps to reproduce:
1. Open a buffer
2. Enter insert mode
3. Type: `<C-o>zz`

What happens:

`zz` is executed, but you see the text `:call context#update('zz')` inserted.

What should happen:
`zz` should be executed and no text inserted.

Tested on latest neovim.

**Comment by wellle** [comment]
Thank you! I can reproduce this and will look into it 👍

**Comment by wellle** [comment]
@nkakouros: Thanks again, should be fixed now 👍

**Comment by nkakouros** [comment]
Thank you! Such a trivial-looking thing and it needs edits to 3 files to get fixed :open_mouth:
