### ISSUE TITLE
Context window not in correct position when using split windows

### ISSUE THREAD

**Issue by unphased** [wellle/context.vim#8]
The context window doesn't follow the active window, so usually what happens with splits is the context stays up at the top left (or wherever it comes up) even when we start navigating a different buffer window.

**Comment by wellle** [comment]
Thank you! This is something I want to look into again 👍

**Comment by wellle** [comment]
@unphased @rafi: I just merged #19 which makes the preview window follow the active window. Please try again. ✌️
