### ISSUE TITLE
Cannot open file on first line

### ISSUE THREAD

**Issue by Nicholas42** [wellle/context.vim#95]
When trying to open a file on the first line with context.vim enabled (either by `vim <Filename>` or `vim +1 <Filename>`) the file will actually be opened on the second line. For all other line numbers there is no problem (i.e. `vim +42 <Filename>` will open the file on line 42 and not 43). 

I hope this is not too petty an issue, but it is kind of annoying when you use vim as an editor for git commit messages.

**Comment by wellle** [comment]
Thank you for opening this issue. I can reproduce it and will try to look into this soon 👍

**Comment by wellle** [comment]
@Nicholas42: Should be fixed by #98. Thank again for reporting 👍
