### ISSUE TITLE
Disable default 'H' mapping

### ISSUE THREAD

**Issue by himat** [wellle/context.vim#99]
The default mapping in this plugin
`nnoremap <silent> <expr> H     context#util#map_H()`
is interfering with my existing mapping of the H key.

How do I disable the mapping from this plugin in my .vimrc?

I tried adding my mapping of `nnoremap H :bp<CR>` after the plugin section in my .vimrc, but that still isn't overwriting the plugin mapping.

Can an option be added to disable or change the default mappings?

**Comment by wellle** [comment]
Hey, please try adding this to your vimrc:
```vim
let g:context_add_mappings = 0

nnoremap <silent> <expr> <C-Y> context#util#map('<C-Y>')
nnoremap <silent> <expr> <C-E> context#util#map('<C-E>')
nnoremap <silent> <expr> zz    context#util#map('zz')
nnoremap <silent> <expr> zb    context#util#map('zb')
nnoremap <silent> <expr> zt    context#util#map_zt()
```

So this first disables all mappings and then adds back all mappings except the `H` one.
